name       : xsetroot
version    : 1.1.2
release    : 5
source     :
    - https://www.x.org/releases/individual/app/xsetroot-1.1.2.tar.gz : 9d007f5119be09924ac3a5d2bd506f32e6c164b82633c88d2aff26311e1a2a2b
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xsetroot
description: |
    The xsetroot program allows you to tailor the appearance of the background ("root") window on a workstation display running X.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xbitmaps)
    - pkgconfig(xcursor)
    - pkgconfig(xmuu)
    - pkgconfig(xproto)
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
