name       : xsetroot
version    : 1.1.1
release    : 1
source     :
    - https://www.x.org/releases/individual/app/xsetroot-1.1.1.tar.bz2 : ba215daaa78c415fce11b9e58c365d03bb602eaa5ea916578d76861a468cc3d9
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xsetroot
description: |
    The xsetroot program allows you to tailor the appearance of the background ("root") window on a workstation display running X.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xbitmaps)
    - pkgconfig(xcursor)
    - pkgconfig(xmuu)
    - pkgconfig(xproto)
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
